[package]
name = 'encointer-runtime'
# major.minor revision must match collator node
# patch revision must match runtime spec_version
version = '1.5.16'
authors = ["Encointer <info@encointer.org>"]
license = "GPL-3.0"
edition = "2021"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = [
    "derive",
] }
log = { version = "0.4.19", default-features = false }
parachain-info = { default-features = false, git = "https://github.com/paritytech/cumulus", branch = "master" }
scale-info = { version = "2.9.0", default-features = false, features = [
    "derive",
] }
serde = { version = "1.0.171", default-features = false, optional = true, features = [
    "derive",
] }

# encointer deps
encointer-balances-tx-payment = { default-features = false, git = "https://github.com/encointer/pallets", branch = "fellowship" }
encointer-balances-tx-payment-rpc-runtime-api = { default-features = false, git = "https://github.com/encointer/pallets", branch = "fellowship" }
encointer-primitives = { default-features = false, git = "https://github.com/encointer/pallets", branch = "fellowship" }
pallet-encointer-balances = { default-features = false, git = "https://github.com/encointer/pallets", branch = "fellowship" }
pallet-encointer-bazaar = { default-features = false, git = "https://github.com/encointer/pallets", branch = "fellowship" }
pallet-encointer-bazaar-rpc-runtime-api = { default-features = false, git = "https://github.com/encointer/pallets", branch = "fellowship" }
pallet-encointer-ceremonies = { default-features = false, git = "https://github.com/encointer/pallets", branch = "fellowship" }
pallet-encointer-ceremonies-rpc-runtime-api = { default-features = false, git = "https://github.com/encointer/pallets", branch = "fellowship" }
pallet-encointer-communities = { default-features = false, git = "https://github.com/encointer/pallets", branch = "fellowship" }
pallet-encointer-communities-rpc-runtime-api = { default-features = false, git = "https://github.com/encointer/pallets", branch = "fellowship" }
pallet-encointer-faucet = { default-features = false, git = "https://github.com/encointer/pallets", branch = "fellowship" }
pallet-encointer-reputation-commitments = { default-features = false, git = "https://github.com/encointer/pallets", branch = "fellowship" }
pallet-encointer-scheduler = { default-features = false, git = "https://github.com/encointer/pallets", branch = "fellowship" }


# Substrate dependencies
frame-try-runtime = { git = "https://github.com/paritytech/substrate.git", default-features = false, optional = true , branch = "master" }
sp-api = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "master" }
sp-block-builder = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "master" }
sp-consensus-aura = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "master" }
sp-core = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "master" }
sp-inherents = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "master" }
sp-io = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "master" }
sp-offchain = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "master" }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "master" }
sp-session = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "master" }
sp-std = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "master" }
sp-transaction-pool = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "master" }
sp-version = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "master" }
try-runtime-cli = { git = "https://github.com/paritytech/substrate.git", default-features = false, optional = true , branch = "master" }

frame-executive = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "master" }
frame-support = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "master" }
frame-system = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "master" }
frame-system-rpc-runtime-api = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "master" }
pallet-asset-tx-payment = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "master" }
pallet-aura = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "master" }
pallet-balances = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "master" }
pallet-collective = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "master" }
pallet-insecure-randomness-collective-flip = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "master" }
pallet-membership = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "master" }
pallet-proxy = { git = "https://github.com/paritytech/substrate.git", default-features = false, branch = "master" }
pallet-scheduler = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "master" }
pallet-timestamp = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "master" }
pallet-transaction-payment = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "master" }
pallet-transaction-payment-rpc-runtime-api = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "master" }
pallet-treasury = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "master" }
pallet-utility = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "master" }

parachains-common = { default-features = false, git = "https://github.com/paritytech/cumulus", branch = "master" }

# Cumulus dependencies
cumulus-pallet-aura-ext = { git = "https://github.com/paritytech/cumulus", default-features = false, branch = "master" }
cumulus-pallet-dmp-queue = { git = "https://github.com/paritytech/cumulus", default-features = false, branch = "master" }
cumulus-pallet-parachain-system = { git = "https://github.com/paritytech/cumulus", default-features = false, branch = "master" }
cumulus-pallet-xcm = { git = "https://github.com/paritytech/cumulus", default-features = false, branch = "master" }
cumulus-pallet-xcmp-queue = { git = "https://github.com/paritytech/cumulus", default-features = false, branch = "master" }
cumulus-primitives-core = { git = "https://github.com/paritytech/cumulus", default-features = false, branch = "master" }
cumulus-primitives-timestamp = { git = "https://github.com/paritytech/cumulus", default-features = false, branch = "master" }
cumulus-primitives-utility = { git = "https://github.com/paritytech/cumulus", default-features = false, branch = "master" }

# Polkadot dependencies
pallet-xcm = { git = "https://github.com/paritytech/polkadot", default-features = false, branch = "master" }
polkadot-parachain = { git = "https://github.com/paritytech/polkadot", default-features = false, branch = "master" }
polkadot-runtime-common = { git = "https://github.com/paritytech/polkadot", default-features = false, branch = "master" }
xcm = { git = "https://github.com/paritytech/polkadot", default-features = false, branch = "master" }
xcm-builder = { git = "https://github.com/paritytech/polkadot", default-features = false, branch = "master" }
xcm-executor = { git = "https://github.com/paritytech/polkadot", default-features = false, branch = "master" }

# Used for runtime benchmarking
frame-benchmarking = { version = "4.0.0-dev", default-features = false, optional = true, git = "https://github.com/paritytech/substrate", branch = "master" }
frame-system-benchmarking = { version = "4.0.0-dev", default-features = false, optional = true, git = "https://github.com/paritytech/substrate", branch = "master" }
hex-literal = { version = "0.3.1", optional = true }

[build-dependencies]
substrate-wasm-builder = { git = "https://github.com/paritytech/substrate", branch = "master" }

[features]
default = ["std"]
runtime-benchmarks = [
    "frame-benchmarking/runtime-benchmarks",
    "frame-support/runtime-benchmarks",
    "frame-system-benchmarking/runtime-benchmarks",
    "hex-literal",
    "sp-runtime/runtime-benchmarks",
    "xcm-builder/runtime-benchmarks",
    "xcm-executor/runtime-benchmarks",
    "pallet-xcm/runtime-benchmarks",
    # actual pallets to be benchmarked
    "cumulus-pallet-xcmp-queue/runtime-benchmarks",
    "frame-system/runtime-benchmarks",
    "pallet-balances/runtime-benchmarks",
    "pallet-collective/runtime-benchmarks",
    "pallet-membership/runtime-benchmarks",
    "pallet-proxy/runtime-benchmarks",
    "pallet-timestamp/runtime-benchmarks",
    "pallet-treasury/runtime-benchmarks",
    "pallet-utility/runtime-benchmarks",
    "pallet-encointer-balances/runtime-benchmarks",
    "pallet-encointer-bazaar/runtime-benchmarks",
    "pallet-encointer-ceremonies/runtime-benchmarks",
    "pallet-encointer-communities/runtime-benchmarks",
    "pallet-encointer-faucet/runtime-benchmarks",
    "pallet-encointer-reputation-commitments/runtime-benchmarks",
    "pallet-encointer-scheduler/runtime-benchmarks",
]
std = [
    "codec/std",
    "scale-info/std",
    "serde",
    "log/std",
    "sp-api/std",
    "sp-std/std",
    "sp-io/std",
    "sp-core/std",
    "sp-runtime/std",
    "sp-version/std",
    "sp-offchain/std",
    "sp-session/std",
    "sp-block-builder/std",
    "sp-transaction-pool/std",
    "sp-inherents/std",
    "frame-support/std",
    "frame-executive/std",
    "frame-system/std",
    "frame-system-rpc-runtime-api/std",
    "pallet-asset-tx-payment/std",
    "pallet-balances/std",
    "pallet-collective/std",
    "pallet-membership/std",
    "pallet-proxy/std",
    "pallet-insecure-randomness-collective-flip/std",
    "pallet-timestamp/std",
    "pallet-transaction-payment/std",
    "pallet-transaction-payment-rpc-runtime-api/std",
    "pallet-treasury/std",
    "pallet-utility/std",
    "pallet-xcm/std",
    "parachain-info/std",
    "parachains-common/std",
    "cumulus-pallet-aura-ext/std",
    "cumulus-pallet-dmp-queue/std",
    "cumulus-pallet-parachain-system/std",
    "cumulus-pallet-xcmp-queue/std",
    "cumulus-pallet-xcm/std",
    "cumulus-primitives-core/std",
    "cumulus-primitives-timestamp/std",
    "cumulus-primitives-utility/std",
    "xcm/std",
    "xcm-builder/std",
    "xcm-executor/std",
    "pallet-aura/std",
    "sp-consensus-aura/std",
    "serde/std",
    # encointer
    "encointer-balances-tx-payment/std",
    "encointer-balances-tx-payment-rpc-runtime-api/std",
    "encointer-primitives/std",
    "encointer-primitives/serde_derive",
    "pallet-encointer-balances/std",
    "pallet-encointer-bazaar/std",
    "pallet-encointer-bazaar-rpc-runtime-api/std",
    "pallet-encointer-ceremonies/std",
    "pallet-encointer-ceremonies-rpc-runtime-api/std",
    "pallet-encointer-communities/std",
    "pallet-encointer-communities-rpc-runtime-api/std",
    "pallet-encointer-faucet/std",
    "pallet-encointer-reputation-commitments/std",
    "pallet-encointer-scheduler/std",
    "frame-try-runtime/std",
]


try-runtime = [
    "frame-try-runtime/try-runtime",
    "frame-system/try-runtime",
    "frame-executive/try-runtime",
    "cumulus-pallet-parachain-system/try-runtime",
    "pallet-insecure-randomness-collective-flip/try-runtime",
    "pallet-timestamp/try-runtime",
    "parachain-info/try-runtime",
    "pallet-balances/try-runtime",
    "pallet-transaction-payment/try-runtime",
    "pallet-asset-tx-payment/try-runtime",
    "pallet-aura/try-runtime",
    "cumulus-pallet-aura-ext/try-runtime",
    "cumulus-pallet-xcmp-queue/try-runtime",
    "pallet-xcm/try-runtime",
    "cumulus-pallet-xcm/try-runtime",
    "cumulus-pallet-dmp-queue/try-runtime",
    "pallet-utility/try-runtime",
    "pallet-treasury/try-runtime",
    "pallet-proxy/try-runtime",
    "pallet-scheduler/try-runtime",
    "pallet-collective/try-runtime",
    "pallet-membership/try-runtime",
    "pallet-encointer-scheduler/try-runtime",
    "pallet-encointer-ceremonies/try-runtime",
    "pallet-encointer-communities/try-runtime",
    "pallet-encointer-balances/try-runtime",
    "pallet-encointer-bazaar/try-runtime",
    "pallet-encointer-faucet/try-runtime",
    "pallet-encointer-reputation-commitments/try-runtime",
]
